services:
  - type: web
    name: superleague-derby-analytics
    env: python
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
