services:
  - type: web
    name: superleague-derby-analytics
    runtime: python-3.11.9  
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
